# Generated by Django 5.2.6 on 2025-09-21 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Balance'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='email',
            field=models.EmailField(default='test@test.com', max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
