# Generated by Django 5.2.6 on 2025-09-22 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_teammember_balance_teammember_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Amount')),
                ('proof_picture', models.ImageField(upload_to='payment_proofs', verbose_name='Proof picture')),
                ('completed', models.BooleanField(default=False, verbose_name='Completed')),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.teammember', verbose_name='Made by')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['completed'],
            },
        ),
    ]
