# Generated by Django 5.2.6 on 2025-09-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='proof_picture',
            field=models.ImageField(blank=True, upload_to='payment_proofs', verbose_name='Proof picture'),
        ),
    ]
