# Generated by Django 5.2.6 on 2025-09-23 16:10

from django.db import migrations, models
from django.db.models import Sum, F, DecimalField

def populate_order_items_and_totals(apps, schema_editor):
    Order = apps.get_model('shop', 'Order')
    OrderItem = apps.get_model('shop', 'OrderItem')

    # To fix OrderItem.unit_price
    for item in OrderItem.objects.all().select_related("product"):
        item.unit_price = item.product.price
        item.save(update_fields=["unit_price"])

    # To fix Order.total_amount
    for order in Order.objects.all():
        total = order.items.aggregate(
            total=Sum(
                F("quantity") * F("product__price"),
                output_field=DecimalField(max_digits=10, decimal_places=2),
            )
        )["total"] or 0
        order.total_amount = total
        order.save(update_fields=["total_amount"])


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_payment_proof_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total amount', null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Unit price', null=True),
        ),
        migrations.RunPython(populate_order_items_and_totals, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total amount'),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Unit price'),
        ),
        migrations.AddField(
            model_name='product',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Visible'),
        ),
    ]
