# Generated by Django 5.2.6 on 2025-10-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_total_amount_orderitem_unit_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Visible'),
        ),
    ]
