# Generated by Django 5.2.6 on 2025-10-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_cost_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cost_price',
        ),
        migrations.AddField(
            model_name='product',
            name='btw',
            field=models.PositiveSmallIntegerField(choices=[(1.0, '0%'), (1.09, '9%'), (1.21, '21%')], default=1.09, verbose_name='BTW-%'),
        ),
        migrations.AddField(
            model_name='product',
            name='cost_ex_btw',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total cost for full package, excluding BTW', max_digits=5, verbose_name='Cost Price (ex. BTW)'),
        ),
        migrations.AddField(
            model_name='product',
            name='pack_size',
            field=models.PositiveIntegerField(default=24, help_text='Number of units in the package', verbose_name='Pack Size'),
        ),
    ]
