# Generated by Django 5.2.6 on 2025-10-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_product_cost_price_product_btw_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='btw',
            field=models.PositiveSmallIntegerField(choices=[(9, '9%'), (0, '0%'), (21, '21%')], default=9, verbose_name='BTW-%'),
        ),
    ]
