# Generated by Django 5.2.6 on 2025-11-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_product_btw'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('margin_percentage', models.DecimalField(decimal_places=2, default=10.0, help_text='This margin applies to all products', max_digits=5, verbose_name='Margin (%)')),
            ],
            options={
                'verbose_name': 'Shop settings',
                'verbose_name_plural': 'Shop settings',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
