name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to PythonAnywhere
        uses: umuttopalak/pythonanywhere-deploy-action@v1.1.2
        with:
          host: www.pythonanywhere.com
          username: ${{ secrets.PA_USERNAME }}
          api_token: ${{ secrets.PA_API_TOKEN }}
          domain_name: ${{ secrets.PA_DOMAIN }}